"""Initial schema with all 8 tables.

Revision ID: 001
Revises:
Create Date: 2026-01-21

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create recipes table
    op.create_table(
        "recipes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("ingredients", sa.JSON(), nullable=True),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("cuisine", sa.String(length=100), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    # Create meal_plans table
    op.create_table(
        "meal_plans",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("week_start_date", sa.Date(), nullable=False),
        sa.Column("meals", sa.JSON(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PLANNING", "FINALIZED", "COMPLETED", name="mealplanstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("week_start_date"),
    )

    # Create shopping_lists table
    op.create_table(
        "shopping_lists",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("items", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "ORDERED", name="shoppingliststatus"),
            nullable=False,
        ),
        sa.Column("ordered_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    # CRITICAL: Create partial unique index to ensure only ONE active list at a time
    # This is PostgreSQL-specific and cannot be auto-generated by Alembic
    op.execute("""
        CREATE UNIQUE INDEX idx_one_active_list
        ON shopping_lists (status)
        WHERE status = 'ACTIVE'
    """)

    # Create pantry_items table
    op.create_table(
        "pantry_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("item_name", sa.String(length=255), nullable=False),
        sa.Column("last_purchase_date", sa.Date(), nullable=True),
        sa.Column("quantity", sa.Float(), nullable=True),
        sa.Column("unit", sa.String(length=50), nullable=True),
        sa.Column("auto_reorder", sa.Boolean(), nullable=False),
        sa.Column("reorder_threshold_days", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    # Create preferences table
    op.create_table(
        "preferences",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user", sa.String(length=50), nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    # Create brand_preferences table
    op.create_table(
        "brand_preferences",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("generic_item", sa.String(length=255), nullable=False),
        sa.Column("preferred_brand", sa.String(length=255), nullable=False),
        sa.Column("kroger_product_id", sa.String(length=100), nullable=True),
        sa.Column(
            "confidence",
            sa.Enum("CONFIRMED", "INFERRED", name="brandconfidence"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("generic_item"),
    )

    # Create conversations table (depends on shopping_lists)
    op.create_table(
        "conversations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("shopping_list_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("user", sa.String(length=50), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("response", sa.Text(), nullable=True),
        sa.Column("context_snapshot", sa.JSON(), nullable=True),
        sa.Column("assistant_model", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum("SUCCESS", "PARSE_ERROR", "API_ERROR", name="conversationstatus"),
            nullable=False,
        ),
        sa.Column("slack_user_id", sa.String(length=50), nullable=True),
        sa.Column("slack_message_ts", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["shopping_list_id"],
            ["shopping_lists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # Create recipe_notes table (depends on recipes)
    op.create_table(
        "recipe_notes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=True),
        sa.Column("recipe_name", sa.String(length=255), nullable=False),
        sa.Column("recipe_name_normalized", sa.String(length=255), nullable=False),
        sa.Column("user", sa.String(length=50), nullable=False),
        sa.Column("note_text", sa.Text(), nullable=False),
        sa.Column(
            "note_type",
            sa.Enum(
                "INGREDIENT_CHANGE", "TECHNIQUE", "TIMING", "GENERAL", name="notetype"
            ),
            nullable=False,
        ),
        sa.Column(
            "outcome",
            sa.Enum("BETTER", "WORSE", "NEUTRAL", name="noteoutcome"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # Create index on recipe_name_normalized for faster lookups
    op.create_index(
        "ix_recipe_notes_recipe_name_normalized",
        "recipe_notes",
        ["recipe_name_normalized"],
    )


def downgrade() -> None:
    # Drop tables in reverse order (respect foreign keys)
    op.drop_index("ix_recipe_notes_recipe_name_normalized", table_name="recipe_notes")
    op.drop_table("recipe_notes")
    op.drop_table("conversations")
    op.drop_table("brand_preferences")
    op.drop_table("preferences")
    op.drop_table("pantry_items")

    # Drop partial unique index before dropping shopping_lists
    op.execute("DROP INDEX IF EXISTS idx_one_active_list")
    op.drop_table("shopping_lists")

    op.drop_table("meal_plans")
    op.drop_table("recipes")

    # Drop enum types
    op.execute("DROP TYPE IF EXISTS noteoutcome")
    op.execute("DROP TYPE IF EXISTS notetype")
    op.execute("DROP TYPE IF EXISTS conversationstatus")
    op.execute("DROP TYPE IF EXISTS brandconfidence")
    op.execute("DROP TYPE IF EXISTS shoppingliststatus")
    op.execute("DROP TYPE IF EXISTS mealplanstatus")
